### ISSUE TITLE
More ideas for EDA?

### ISSUE THREAD

**Issue by jackattackyang** [UBC-MDS/DSCI_522_Pokemon_Legendariness_Classifier#9]
Right now our EDA contains 2 graphs. 
A bar graph showing the legendary vs non-legendary counts and a boxplot comparing stats between legendary and non-legendary pokemon.
Is this enough you think? I could not think of other data trends to represent that are unique enough.

**Comment by RayceRossum** [comment]
I really like the boxplot over the stats categories, looks extremely positive that our model will be successful.

In terms of other EDA's, an idea I had was doing some "key" permutations of stats. (HP and DEF, ATK and SPEED, etc..) in order to get a few more features and possibly get rid of some of those outliers. Although I imagine that's just part of the pokemonData script and the visuals can be updated accordingly
